version: "3.9"

services:
  PC1:
    image: labredes
    container_name: PC1
    entrypoint: ["/bin/sh"]
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
    volumes:
      - /mnt/traffic_tunnel:/home
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      - lab

  PC2:
    image: labredes
    container_name: PC2
    entrypoint: ["/bin/sh"]
    stdin_open: true
    tty: true
    ports:
      - "8082:8080"
    volumes:
      - /mnt/traffic_tunnel:/home
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      - lab

  PC3:
    image: labredes
    container_name: PC3
    entrypoint: ["/bin/sh"]
    stdin_open: true
    tty: true
    ports:
      - "8083:8080"
    volumes:
      - /mnt/traffic_tunnel:/home
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      - lab

networks:
  lab:
    external: true